find_package(Git REQUIRED)
if(GIT_FOUND)
  message("git found: ${GIT_EXECUTABLE}")
endif()

find_package(GTest)
if (NOT GTest_FOUND)
  include(src/cmake/find_or_download_gtest.cmake REQUIRED)
else(NOT GTest_FOUND)
  include_directories(${GTEST_INCLUDE_DIRS})
endif(NOT GTest_FOUND)
